spring:
  application:
    name: Config-Server-Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShaikMoinbasha/Configurations
          clone-on-start: true
          default-label: main
server:
  port: 8181
